# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java
 
 
trigger:
- master
 
pool:
  vmImage: Ubuntu-latest
 
steps:
- task: Maven@3
  inputs:
    mavenPomFile: '/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '17.0.0'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean compile test'
- bash: |
    token=$(curl -H "Content-Type: application/json" -X POST --data '{ "client_id": "$(client_id)","client_secret": "$(client_secret)" }' https://xray.cloud.getxray.app/api/v2/authenticate| tr -d '"')
    curl -H "Content-Type: text/xml" -X POST -H "Authorization: Bearer ${token}" --data @xrayJunitAzureIntegration/target/surefire-reports/pom.xml https://xray.cloud.getxray.app/api/v2/import/execution/junit?projectKey=TSTNGWTHSH
